export default function Head() {
  return (
    <>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <title>{"Yotëi"}</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <meta name="keywords" content="yotei,plan,schedule,csulb,lbsu,course" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
